### ISSUE TITLE
安装之后大面积飙红

### ISSUE THREAD

**Issue by wu5288540** [lgc2333/nonebot-plugin-picstatus#10]
安装这个插件之后，启动nbot会大面积报错，包括本插件在内，全部error，看了下日志，显示nbot的原始文件出现各种错误，core dumped，卸载本插件之后也修不好，必须重新把那部分报错的插件重新安装一次才能修好，修好之后再安装本插件，则重复报错循环，确定无法和部分插件共存。
核心原因好像是因为动了nbot的core，click等关键文件，导致部分需求核心的插件光速滑跪
但精力有限，暂时未排查出根源是本插件或是其他插件，但安装这个插件后我的其他插件挂了70%疯狂跳红报错属实是有点壮观……

**Comment by lgc2333** [comment]
请问你之前的nb2版本是？
我在插件依赖写的是2.0.0b5，如果真的有需求的话我会考虑降依赖中nb版本

**Comment by wu5288540** [comment]
目前在用的应该是2.0.0b2，用脚手架安装的

**Comment by lgc2333** [comment]
请升级nb2至2.0.0b4以上，否则无法使用本插件
