### ISSUE TITLE
'NoneType' object has no attribute 'max'

### ISSUE THREAD

**Issue by mmmjie** [lgc2333/nonebot-plugin-picstatus#11]
![MZE6}M78BGZB_ZK8{VFZZ)6](https://user-images.githubusercontent.com/45615222/197262275-a1d8eebd-9a8c-4889-a27d-a6d76e2d4f58.png)

Ubuntu 20.04.4 LTS (GNU/Linux 5.15.0-1018-oracle aarch64)

请问这咋处理啊

**Comment by lgc2333** [comment]
获取cpu占用率失败
试试`sudo nb run`启动nonebot

**Comment by mmmjie** [comment]
> 获取cpu占用率失败尝试启动 nonebot`sudo nb run`

之前就是root 启动的，会不会和arm的CPU有关？不是amd的

**Comment by lgc2333** [comment]
这我就不清楚了((
可以去看看 psutil 库的问题之类的
