### ISSUE TITLE
可否增加代理状态显示

### ISSUE THREAD

**Issue by Jerry-FaGe** [lgc2333/nonebot-plugin-picstatus#13]
大佬可不可以找个地方加个类似于下图的代理状态显示（用户应该是 Linux 专有就不麻烦啦）
![3D0FE4}FV}TU {HJ_5KK{35](https://user-images.githubusercontent.com/40235071/201273842-08a778c1-68a7-4ec1-ae2a-48b85b3e273b.PNG)

**Comment by lgc2333** [comment]
到时候弄自定义proxy和网址 显示标题之类的吧

**Comment by lgc2333** [comment]
可以在网速显示的底下画个横线加

**Comment by Jerry-FaGe** [comment]
> 可以在网速显示的底下画个横线加

会不会有些奇怪，感觉新开一个遮罩块加也可以

**Comment by lgc2333** [comment]
> > 可以在网速显示的底下画个横线加
> 
> 会不会有些奇怪，感觉新开一个遮罩块加也可以

可以参考硬盘下面那个读写速的样子

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/202856122-936557b9-ea7d-4713-8f96-8db50ccf9da2.png)
![image](https://user-images.githubusercontent.com/59048777/202856159-efec9e1e-0d80-48d6-9422-c286caca4883.png)

完成
