### ISSUE TITLE
配置了PS_NEED_AT后仍然不需要艾特就能触发

### ISSUE THREAD

**Issue by forchannot** [lgc2333/nonebot-plugin-picstatus#14]
如题，是群聊里面，我已经配置了这个配置项，并且重启了，但是似乎没生效，仍然不需要艾特就能触发，并且只要一句话前面包含状态就会触发
![Screenshot_2022-11-17-14-45-50-643_mark via](https://user-images.githubusercontent.com/100580891/202375793-19410f44-e9dc-4863-b21f-61d7ea1c9bd1.png)
![Screenshot_2022-11-17-14-47-38-590_com tencent mobileqq](https://user-images.githubusercontent.com/100580891/202376049-7d7b4f29-b751-4311-b3f4-bf80646b27ee.png)

**Comment by forchannot** [comment]
此外，希望当检测到不是超管但发送状态并且没有艾特机器人时不回复任何内容，我的目的就是希望群聊中不会误触，但我看代码似乎任何人发状态不艾特机器人都会回复一句话
![Screenshot_2022-11-17-14-51-24-236_mark via](https://user-images.githubusercontent.com/100580891/202376921-1a050e00-d3bd-4808-a417-ee94999ace24.jpg)

**Comment by lgc2333** [comment]
已修复，等待release
（这几天沉迷于Minecraft）
