### ISSUE TITLE
下载/打开随机背景图失败，使用默认背景图

### ISSUE THREAD

**Issue by M-Riverbank** [lgc2333/nonebot-plugin-picstatus#16]
File "D:\nb\robot\robot\plugins\picstatus\draw.py", line 547, in get_bg
    return Image.open(BytesIO(await get_anime_pic()))
  File "D:\nb\robot\robot\plugins\picstatus\util.py", line 34, in get_anime_pic
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lgc2333** [comment]
不太清楚什么情况，试试在你运行nb2的网络环境打开这个网址
https://api.gmit.vip/Api/DmImg?format=json

**Comment by M-Riverbank** [comment]
> 

隔一段时间又这个报错就消失了,原因不明,推测是短时间内请求太多导致的
