### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by mute23-code** [lgc2333/nonebot-plugin-picstatus#17]
https://github.com/lgc2333/nonebot-plugin-picstatus/blob/3852bfb37aad0035bdfe851bc10715e1deb00e46/nonebot_plugin_picstatus/draw.py#L342

```
its: List[Tuple[str, sdiskusage | Exception]] = disks.items()  # noqa
```
`[str, sdiskusage | Exception]` 中的 `|` 处发生报错

**Comment by lgc2333** [comment]
草 又忘记照顾3.10以下版本py的用户了
这个语法是3.10以上独有的，稍等我一下

**Comment by lgc2333** [comment]
好了，试试看0.3.1版本
