### ISSUE TITLE
linux使用本地背景图插件加载失败

### ISSUE THREAD

**Issue by Xashian** [lgc2333/nonebot-plugin-picstatus#19]
![屏幕截图 2023-01-16 222848](https://user-images.githubusercontent.com/60306014/212706310-d644f654-a41f-4e89-8782-7916f6bb9852.png)
![屏幕截图 2023-01-16 224133](https://user-images.githubusercontent.com/60306014/212706346-a7feb9ee-2692-49f5-8c39-202dd93a8a52.png)
![屏幕截图 2023-01-16 223400](https://user-images.githubusercontent.com/60306014/212706377-9fb27627-a859-4885-b76e-9fa5bd88832f.png)

**Comment by lgc2333** [comment]
有点常识行吗……字符串列表不带引号？你超级用户怎么配置的？
