### ISSUE TITLE
设备未就绪

### ISSUE THREAD

**Issue by liuzj288** [lgc2333/nonebot-plugin-picstatus#2]
![image](https://user-images.githubusercontent.com/13833404/191876856-7df3d3f1-c251-4cc4-be88-e2698998dd06.png)

**Comment by liuzj288** [comment]
emm 找到原因了，只有C盘的话怎么注释掉D盘和E盘

**Comment by lgc2333** [comment]
到时候我做个配置项忽略读取报错的磁盘吧

**Comment by liuzj288** [comment]
> 到时候我做个配置项忽略读取报错的磁盘吧

还有一个问题是插件获取的nickname是QQ用户名而不是env.prof里面配置的bot名，另外能不能把cpu温度，内存温度这些数据也写进图片里

**Comment by lgc2333** [comment]
已更新，本来打算做硬件温度的但是因为windows以及部分linux设备无法读取温度所以就没做了

**Comment by liuzj288** [comment]
> 已更新，本来打算做硬件温度的但是因为windows以及部分linux设备无法读取温度所以就没做了

![6@~(4~{(T(1R0MECHMT%KZD](https://user-images.githubusercontent.com/13833404/192080774-da850269-eca4-43ca-94f4-2053d2e7b5bb.PNG)
怎么网速一直显示为0

**Comment by lgc2333** [comment]
> > 已更新，本来打算做硬件温度的但是因为windows以及部分linux设备无法读取温度所以就没做了
> 
> ![6@(4{(T(1R0MECHMT%KZD](https://user-images.githubusercontent.com/13833404/192080774-da850269-eca4-43ca-94f4-2053d2e7b5bb.PNG) 怎么网速一直显示为0

布吉岛
