### ISSUE TITLE
插件无法导入

### ISSUE THREAD

**Issue by iven13465** [lgc2333/nonebot-plugin-picstatus#3]
![image](https://user-images.githubusercontent.com/95957360/191963229-322fb6f5-1b9e-408f-8636-85b88f11f915.png)

**Comment by lgc2333** [comment]
> ![image](https://user-images.githubusercontent.com/95957360/191963229-322fb6f5-1b9e-408f-8636-85b88f11f915.png)

请使用py3.8及以上版本

**Comment by iven13465** [comment]
> > ![image](https://user-images.githubusercontent.com/95957360/191963229-322fb6f5-1b9e-408f-8636-85b88f11f915.png)
> 
> 请使用py3.8及以上版本

我是3.8.10

**Comment by lgc2333** [comment]
> > > ![image](https://user-images.githubusercontent.com/95957360/191963229-322fb6f5-1b9e-408f-8636-85b88f11f915.png)
> > 
> > 
> > 请使用py3.8及以上版本
> 
> 我是3.8.10

真的假的 那这不应该啊 你在检查一下，确定问题我再修

**Comment by iven13465** [comment]
> > > > ![image](https://user-images.githubusercontent.com/95957360/191963229-322fb6f5-1b9e-408f-8636-85b88f11f915.png)
> > > 
> > > 
> > > 请使用py3.8及以上版本
> > 
> > 我是3.8.10
> 
> 运行 `python -V` 查看py版本


![Screenshot_20220923_223931.jpg](https://user-images.githubusercontent.com/95957360/191987089-08b2d143-9b3f-4410-9064-3a4ff44e9fef.jpg)

**Comment by lgc2333** [comment]
> 

行吧行吧我修一下

**Comment by lgc2333** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/95957360/191963229-322fb6f5-1b9e-408f-8636-85b88f11f915.png)
> > > > 
> > > > 
> > > > 请使用py3.8及以上版本
> > > 
> > > 
> > > 我是3.8.10
> > 
> > 
> > 运行 `python -V` 查看py版本
> 
> ![Screenshot_20220923_223931.jpg](https://user-images.githubusercontent.com/95957360/191987089-08b2d143-9b3f-4410-9064-3a4ff44e9fef.jpg)
> 
> 删掉相关报错代码后就能用了

问一下除了这里还有哪里报错呢

**Comment by iven13465** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/95957360/191963229-322fb6f5-1b9e-408f-8636-85b88f11f915.png)
> > > > > 
> > > > > 
> > > > > 请使用py3.8及以上版本
> > > > 
> > > > 
> > > > 我是3.8.10
> > > 
> > > 
> > > 运行 `python -V` 查看py版本
> > 
> > ![Screenshot_20220923_223931.jpg](https://user-images.githubusercontent.com/95957360/191987089-08b2d143-9b3f-4410-9064-3a4ff44e9fef.jpg)
> > 
> > 删掉相关报错代码后就能用了
> 
> 问一下除了这里还有哪里报错呢

暂时还没发现

**Comment by lgc2333** [comment]
尝试一下新版本
