### ISSUE TITLE
PS_IGNORE_PARTS怎么配置

### ISSUE THREAD

**Issue by fengshao233** [lgc2333/nonebot-plugin-picstatus#5]
怎么写都报错
[D] [D:] ["D"] ["D:"]都试了

**Comment by lgc2333** [comment]
> 怎么写都报错 [D] [D:] ["D"] ["D:"]都试了

试试`["D:\"]

**Comment by fengshao233** [comment]
报错
![MHYNFUD2X (S$N044}0O_3E](https://user-images.githubusercontent.com/110460087/192089085-32b8859c-ac4a-488f-90c0-f3905ec87a51.png)

**Comment by lgc2333** [comment]
> 报错 ![MHYNFUD2X (S$N044}0O_3E](https://user-images.githubusercontent.com/110460087/192089085-32b8859c-ac4a-488f-90c0-f3905ec87a51.png)

配置文件截图

**Comment by lgc2333** [comment]
不对 在json里反斜杠需要转义 试试`["D:\\"]`

**Comment by fengshao233** [comment]
> 不对 在json里反斜杠需要转义 试试`["D:\\"]`

行了 谢谢大佬

**Comment by lgc2333** [comment]
下个版本做一下正则表达式匹配

**Comment by fengshao233** [comment]
> 

可以写个配置项举例
