### ISSUE TITLE
获取运行状态图失败

### ISSUE THREAD

**Issue by NSQX13579** [lgc2333/nonebot-plugin-picstatus#6]
如题，求助
![}5P%W6474 V%5 2 4V)2}BD](https://user-images.githubusercontent.com/102937666/192088599-2c63caa5-8f51-4621-953b-ecaa37d19e67.png)

**Comment by lgc2333** [comment]
> 如题，求助 ![}5P%W6474 V%5 2 4V)2}BD](https://user-images.githubusercontent.com/102937666/192088599-2c63caa5-8f51-4621-953b-ecaa37d19e67.png)

请问GoCQ版本是？

**Comment by NSQX13579** [comment]
> 

v1.0.0-rc1
是版本问题的话，那我更新后再试试

**Comment by lgc2333** [comment]
可以尝试更新一下GoCQ-2022年9月24日 下午4:43，nansha ***@***.***>写道：





v1.0.0-rc1

是版本问题的话，那我更新后再试试

**Comment by NSQX13579** [comment]
> 可以尝试更新一下GoCQ-2022年9月24日 下午4：43，nansha ***@***.***>写道： v1.0.0-rc1 是版本问题的话，那我更新后再试试 —直接回复此电子邮件，在GitHub上查看，或取消订阅.您收到此消息是因为您发表评论。消息编号： >尝试更新gocq-20224年9月24日：43 pm，南沙 * * * ** * .* * * >说：v1.0.0-rc1是一个版本问题，所以我会在更新后重试 ，直接回复这封电子邮件，在GitHub上查看，或者取消订阅。您收到此消息是因为您发表了评论。消息编号：>

已解决，感谢回复
