### ISSUE TITLE
请问这个网速列表怎么忽略

### ISSUE THREAD

**Issue by Kiana1314** [lgc2333/nonebot-plugin-picstatus#7]
![YN(}R}BKO7NVQ9VQ$7IR L3](https://user-images.githubusercontent.com/107671434/192092458-c589b4db-3232-4029-90a4-64f9f1a5711f.png)
![MEXR3H RG6R{TP`O T3RDXH](https://user-images.githubusercontent.com/107671434/192092469-6a522dd1-94a1-47d7-a53b-63092c10d8c0.png)
![}2~A$J20 NX5 J1MUW7~)FP](https://user-images.githubusercontent.com/107671434/192092505-0868ea2b-3290-4168-8057-ef956d081e8b.png)

**Comment by lgc2333** [comment]
打引号

**Comment by lgc2333** [comment]
`["isatap...."]`
