### ISSUE TITLE
更新0.2.3之后寄了

### ISSUE THREAD

**Issue by liuzj288** [lgc2333/nonebot-plugin-picstatus#8]
![image](https://user-images.githubusercontent.com/13833404/192122967-e3396c86-e061-4988-a131-85725b61c48b.png)
![image](https://user-images.githubusercontent.com/13833404/192122983-ee8f9f9c-6828-4c4d-8c98-e145861e0f99.png)

**Comment by lgc2333** [comment]
配置文件正则表达式语法错误

**Comment by liuzj288** [comment]
> 配置文件正则表达式语法错误

咦？只设置了这几个参数呀
![image](https://user-images.githubusercontent.com/13833404/192133711-33e0903d-3d63-4222-901f-0b6e52449dad.png)

**Comment by lgc2333** [comment]
把`D:\\`改成`^D:` `E:\\`同理
原因是反斜杠在正则表达式里也有特殊用途

**Comment by lgc2333** [comment]
改成`D:\\\\$`也可以

**Comment by liuzj288** [comment]
> 改成`^D:\\\\$`也可以

好的，解决了
