### ISSUE TITLE
可否加一个配置来自定义背景图

### ISSUE THREAD

**Issue by bywhite0** [lgc2333/nonebot-plugin-picstatus#9]
如题

可以配置为图片文件的URL或本地路径

**Comment by lgc2333** [comment]
考虑

**Comment by lgc2333** [comment]
https://github.com/lgc2333/nonebot-plugin-picstatus/commit/ba07445b5cb3a249c0e3da0b20e652e1ff08a186

https://github.com/lgc2333/nonebot-plugin-picstatus/releases/tag/0.2.4

**Comment by lgc2333** [comment]
https://github.com/lgc2333/nonebot-plugin-picstatus/releases/tag/0.2.4.post0
